/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'XPipe App',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'program/index'},
      items: [
          'program/shortcut',
          //'cli/example',
          //'cli/tips',
          {
            type: 'category',
            label: 'Conenctions',
            collapsible: true,
            collapsed: true,
            items: [
               // {type: 'autogenerated', dirName: 'cli/man'}
               'program/connections/iot',
               'program/connections/proxmox',
            ],
          },
         {
           type: 'category',
           label: 'Settings',
           collapsible: true,
           collapsed: true,
           items: [
              // {type: 'autogenerated', dirName: 'cli/man'}
              'program/settings/synchronization/synchronization',
              'program/settings/terminal/terminal',
           ],
         }
      ],
    },
    {
      type: 'category',
      label: 'XPipe CLI',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'cli/index'},
      items: [
          'cli/basics',
          //'cli/example',
          //'cli/tips',
        {
          type: 'category',
          label: 'Manpages',
          collapsible: true,
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'cli/man'}
          ],
        }
      ],
    },
    'directories',
    'two-step-connections',
    'preview',
    'license-activation',
    'security',
    'troubleshooting',
    'license',
    {
      type: 'category',
      label: 'Legal',
      collapsible: true,
      collapsed: false,
      items: [
          'terms-of-service',
          'end-user-license-agreement',
          'privacy-policy',
          'reporter-privacy-policy'
        ]
    }
  ],
};

module.exports = sidebars;
