/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'about',
      'installation',    {
      type: 'category',
      label: 'Connections',
      collapsible: false,
      collapsed: false,
      link: {type: 'doc', id: 'connections/index'},
      items: [
        'connections/shell-connections',
        'connections/stream-connections',
        'connections/drains-and-sinks',
      ],
    },
    {
      type: 'category',
      label: 'X-Pipe CLI',
      collapsible: false,
      collapsed: false,
      link: {type: 'doc', id: 'cli/index'},
      items: [
          'cli/basics',
          'cli/example',
          'cli/tips',
        {
          type: 'category',
          label: 'Manpages',
          collapsible: true,
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'cli/man'}
          ],
        }
      ],
    }
  ],
};

module.exports = sidebars;
